title = "Adonis_2.0"
gitRepoUrl = "https://github.com/Sceleratis/Adonis_2.0"
gitSourceBranch = "main"
autoSectionPath = "src/MainModule/Packages"
changelog = true
apiCategories = [
]

[home]
enabled = true
includeReadme = true

[docusaurus]
tagline = "Roblox Server Administration System"
favicon = "/favicon.png"

[[navbar.items]]
href = "https://discord.gg/H5RvTP3"
label = "Discord"
position = "right"

[footer]
style = "dark"
copyright = "Distributed under the <a href='https://github.com/Sceleratis/Adonis_2.0/blob/main/LICENSE' target='_blank'>MIT license.</a> Built with <a href='https://upliftgames.github.io/moonwave/' target='_blank'>Moonwave</a> and <a href='https://docusaurus.io/' target='_blank'>Docusaurus</a>"
